- name: DNS | Install DNS Packages
  yum:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: DNS | Configure named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0644

- name: DNS | Configure named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: 0644
